vd3.3.2.3 mảng con một chiều


In [1]:
import numpy as np
A=np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
A[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [3]:
A[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [4]:
A[4:7]  # elements from index 4 to 6

array([4, 5, 6])

#3.3.2.4 Mảng con đa chiều

In [5]:
import numpy as np
B=np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]])
B

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [ ]:
B [:2, :3]#2 dòng, 3 cột đầu tiên

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
B[:3 , ::2] # lấy các hàng từ 0 đến 3 , # lấy cột với bước nhảy là 2 bắt đầu từ cột 0


array([[1, 3],
       [5, 7],
       [9, 1]])

In [9]:
B[ :: -1, ::-1]  # đảo ngược cả hàng và cột

array([[2, 1, 0, 9],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print( "cột đầu tiên của mảng arr là:", arr[:, 0])  # cột đầu tiên
print("hàng đàu tiên của mảng arr là:", arr[0, :])  # hàng đầu tiên
print("hàng đàu tiên của mảng arr là:", arr[0])  # hàng đầu tiên

cột đầu tiên của mảng arr là: [1 4 7]
hàng đàu tiên của mảng arr là: [1 2 3]
hàng đàu tiên của mảng arr là: [1 2 3]


#3.3.3.1

In [12]:
import numpy as np
# Tạo mảng 2 chiều 3x3
arr_2d = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# Lấy view mới chỉ chứa 2 dòng và 2 cột của mảng gốc
arr_view = arr_2d[:2, :2].view()
print(arr_view) #in mảng con arr_con vừa được slicing từ hàm view

[[1 2]
 [4 5]]


In [13]:
# Thay đổi giá trị trong view
arr_view[0, 0] = 100 #Chỉnh sửa phần tử ở dòng 0, cột 0 thành 10.
print(arr_view) #in ra mảng con sau khi chỉnh sửa.


[[100   2]
 [  4   5]]


In [14]:
print("Mảng gốc sau khi thay đổi giá trị trong view:")
print(arr_2d) #in ra mảng arr ban đầu. 


Mảng gốc sau khi thay đổi giá trị trong view:
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [15]:
sub_arr=arr[:2,:2] #slicing mảng con lấy 2 dòng, 2 cột của mảng arr
print(sub_arr) #in mảng con arr_con vừa được slicing


[[1 2]
 [4 5]]


In [16]:
sub_arr[0,0]=10 #Chỉnh sửa phần tử ở dòng 0, cột 0 của mảng con thành 10.
print(sub_arr) #in ra mảng con sau khi chỉnh sửa.

[[10  2]
 [ 4  5]]


In [17]:
print(arr) #in ra mảng arr ban đầu

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [19]:
sub_arr_copy=arr[:2,:2].copy() #Thêm phương thức copy().
print(sub_arr_copy) #in mảng con vừa được copy.

[[10  2]
 [ 4  5]]


In [20]:
sub_arr_copy[0,0]=10 #sửa phần tử ở dòng 0, cột 0 của mảng
 # copy thành 10.
print(sub_arr_copy)

[[10  2]
 [ 4  5]]


In [21]:
print(arr) #In ra mảng arr ban đầu

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


#vd 3.3.3.4

In [22]:
arr=np.arange(1,10) #Tạo mảng một chiều arr có 9 phần tử từ 1-9
grid= arr.reshape((3,3))#chuyển đổi mảng arr thành mảng grid, 3x3
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#3.3.3.5 tạo một ma trận hàng từ mảng một chiều

In [23]:
x = np.array([1, 2, 3])
x.reshape((1, 3)) #tạo ma trận hàng thông qua reshape.

array([[1, 2, 3]])

In [26]:
x[np.newaxis, :] #Tạo ma trận hàng (thêm trục dọc/thêm hàng) thông qua newaxis.

array([[1, 2, 3]])

In [27]:
x.reshape((3, 1)) #Tạo ma trận cột thông reshape.

array([[1],
       [2],
       [3]])

In [28]:
x[:,np.newaxis] #(thêm trục ngang /thêm cột) thông qua newaxis

array([[1],
       [2],
       [3]])

#3.3.4.2

In [29]:
import numpy as np
a = np.array([[1, 2],
 [3, 4]])
b = np.array([[5, 6],
 [7, 8]])
# Kết hợp theo chiều đầu tiên (trục dọc/ trục 0) của mảng
c = np.vstack((a, b))
# Kết hợp theo chiều ngang (trục ngang/ trục 1) của mảng
d = np.hstack((a,b))
print(c)
print(d)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


#3.3.4.3

In [30]:
import numpy as np
arr = np.arange(10) #Tạo mảng arr gồm 10 phần tử từ 0-9
sub_arr1=np.split(arr,[3, 6]) #chia mảng arr theo chỉ mục [3, 6]
#Phần đầu tiên bắt đầu từ chỉ mục 0 và kết thúc trước chỉ mục 3.
#Phần thứ hai bắt đầu từ chỉ mục 3 và kết thúc trước chỉ mục 6.
sub_arr2=np.split(arr,2) #chia mảng arr thành 2 phần bằng nhau
print("Mảng con sub_arr1 là:", sub_arr1, "\n")
print("Mảng con sub_arr2 là:", sub_arr2)


Mảng con sub_arr1 là: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])] 

Mảng con sub_arr2 là: [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


#3.3.4.4

In [31]:
import numpy as np
arr = np.arange(16).reshape((4,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
upper,lower = np.vsplit(arr,2) #Tách theo trục ngang
print("Kết quả sau khi tách từ mảng ban đầu \n")
print(upper,"\n")
print(lower,"\n")

Kết quả sau khi tách từ mảng ban đầu 

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]] 



In [33]:
left,right=np.hsplit(arr,2) #Tách theo trục dọc
print("Kết quả sau khi tách từ mảng ban đầu \n")
print(left,"\n")
print(right,"\n")


Kết quả sau khi tách từ mảng ban đầu 

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]] 



#3.3.5

In [34]:
import numpy as np
arr=np.array([1,2,3])
new_arr=np.append(arr,4)
print(arr)
print(new_arr)


[1 2 3]
[1 2 3 4]


#Ví dụ 3.3.5.2: Thêm phần tử vào vị trí cụ thể trong mảng 1 chiều:

In [35]:
#Thêm phần tử vào vị trí cụ thể trong mảng 1 chiều:
arr = np.array([1, 2, 3, 4, 5])
new_element = 10
index_to_insert = 2
new_arr = np.insert(arr, index_to_insert, new_element)
print(new_arr)

[ 1  2 10  3  4  5]


In [36]:
#Thêm phần tử vào vị trí cụ thể trong mảng 2 chiều:
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
new_element = [7, 8]
row_to_insert = 1
new_arr_2d=np.insert(arr_2d,row_to_insert,new_element,axis=0)
print(new_arr_2d)

[[1 2]
 [7 8]
 [3 4]
 [5 6]]


#Ví dụ 3.3.6.1. Tìm phần tử có giá trị x trong một mảng numpy.

In [37]:
#Tìm chỉ mục (vị trí) phần tử trong mảng 1 chiều:
arr = np.array([1, 2, 3, 4, 5])
indices = np.where(arr==3)
indices

(array([2]),)

#Ví dụ 3.3.6.2

In [38]:
arr = np.array([1, 2, 3, 4, 5])
indices = np.argwhere(arr==3)
indices

array([[2]])

#Ví dụ 3.3.6.3.

In [39]:
arr = np.array([1, 5, 2, 3, 4])
max_idx = np.argmax(arr)
min_idx = np.argmin(arr)
print(max_idx)
print(min_idx)


1
0


#Ví dụ 3.3.6.4.

In [40]:
arr = np.array([1, 2, 3, 4, 5])
sorted_arr = np.sort(arr)
sorted_arr

array([1, 2, 3, 4, 5])

In [41]:
arr = np.array([1, 2, 3, 4, 5])
arr.sort()
arr

array([1, 2, 3, 4, 5])

In [42]:
arr = np.array([3, 1, 4, 2, 5])
sorted_arr_descending= np.sort(arr)[::-1]
sorted_arr_descending

array([5, 4, 3, 2, 1])

In [43]:
arr = np.array([3, 1, 4, 2, 5])
arr.sort()
arr[::-1]

array([5, 4, 3, 2, 1])

#Ví dụ 3.3.7.1.

In [44]:
#Xóa một phần tử ở vị trí trong mảng
arr = np.array([3, 1, 4, 2, 5])
idx_to_delete = 2 #Xóa phần tử 4 ở chỉ mục 2.
new_arr=np.delete(arr,idx_to_delete)
new_arr

array([3, 1, 2, 5])

In [45]:
#Xóa nhiểu phần tử trong mảng
arr = np.array([3, 1, 4, 2, 5])
idx_to_delete = [1, 3]
new_arr = np.delete(arr, idx_to_delete)
new_arr

array([3, 4, 5])

In [47]:
#Xóa phần tử trên mảng 2 chiều
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_idx_to_delete = 1
new_arr_2d = np.delete(arr_2d, row_idx_to_delete, axis=0)

#3.3.8.1

In [48]:
import numpy as np
# Định nghĩa kiểu dữ liệu cho một Structured Array
dtype = [('name', 'U20'), ('age', int), ('height', float)]
# Tạo một Structured Array
data = np.array([('Minh', 22, 181.3),
('Lan', 40, 160.6),
('Linh', 31, 163.2),
('Lương',18,175.5),
('Thanh',50, 165.0)], dtype=dtype)
print(data)
print(data.dtype)

[('Minh', 22, 181.3) ('Lan', 40, 160.6) ('Linh', 31, 163.2)
 ('Lương', 18, 175.5) ('Thanh', 50, 165. )]
[('name', '<U20'), ('age', '<i8'), ('height', '<f8')]


#Ví dụ 3.3.8.2

In [49]:
import numpy as np
# Định nghĩa kiểu dữ liệu cho một Structured Array
dtype = [('name', 'U20'), ('age', int), ('height', float)]
# Tạo một Structured Array
data = np.array([('Minh', 22, 165.5),
('Lan', 40, 160.0),
('Linh', 31, 165.0),
('Lương',18,166.5),
('Thanh',50, 170.0)], dtype=dtype)
# Truy cập các trường bằng tên
print(data['name']) # In ra mảng 'name'
print(data['age']) # In ra mảng 'age'
print(data['height']) # In ra mảng 'height'

['Minh' 'Lan' 'Linh' 'Lương' 'Thanh']
[22 40 31 18 50]
[165.5 160.  165.  166.5 170. ]


#3.4.1 Tạo mảng NumPy với 100 triệu phần tử kiểu int64. Sau đó thực
hiện tính tổng các phần tử trong mảng Numpy bằng hai cách:

In [1]:
import numpy as np
import time
# Tạo một mảng NumPy với 100.000.000 phần tử
arr = np.arange(100000000, dtype=np.int64)
# Tính tổng các phần tử của mảng bằng vòng lặp
start_time = time.time()
total = np.int64(0)
for num in arr:
 total += num
end_time = time.time()
elapsed_time_loop = end_time - start_time
print("Tổng các phần tử mảng arr khi sử dụng vòng lặp:", total)
print("Thời gian (giây) khi sử dụng vòng lặp:", elapsed_time_loop)
# Tính tổng các phần tử của mảng bằng np.sum()
start_time = time.time()
total = np.sum(arr)
end_time = time.time()
elapsed_time_npsum = end_time - start_time
print("Tổng các phần tử mảng arr khi sử dụng hàm np.sum():", total)
print("Thời gian (giây) khi sử dụng np.sum():", elapsed_time_npsum)
num_times_faster = elapsed_time_loop / elapsed_time_npsum
print("Sử dụng vòng lặp chậm hơn: ~",int(num_times_faster),"lần")

Tổng các phần tử mảng arr khi sử dụng vòng lặp: 4999999950000000
Thời gian (giây) khi sử dụng vòng lặp: 13.188317060470581
Tổng các phần tử mảng arr khi sử dụng hàm np.sum(): 4999999950000000
Thời gian (giây) khi sử dụng np.sum(): 0.06741142272949219
Sử dụng vòng lặp chậm hơn: ~ 195 lần


#Ví dụ 3.4.2. So sánh hiệu suất tính toán giữa Numpy và List trên một ví dụ đơn giản
về tính tổng của một dãy số từ 1 đến 1,000,000.

In [2]:
import numpy as np
import timeit # Import thư viện timeit để đo thời gian thực thi của các đoạn code.
# Tính tổng của mảng sử dụng Numpy
np_setup = "import numpy as np; np_array = np.arange(1, 1000001)"
np_code = "np_sum = np.sum(np_array)"
np_time = timeit.timeit(stmt=np_code, setup=np_setup, number=10)
# Tính tổng của danh sách sử dụng List
list_setup = "list_array = list(range(1, 1000001))"
list_code = "list_sum = sum(list_array)"
list_time = timeit.timeit(stmt=list_code, setup=list_setup,
number=10)
print("Thời gian tính toán của Numpy:", np_time)
print("Thời gian tính toán của List:", list_time)
print("Numpy tính nhanh hơn List ở lượt chạy là ~ ", int(list_time/np_time), "lần!!")

Thời gian tính toán của Numpy: 0.006050899999991088
Thời gian tính toán của List: 0.04126689999998234
Numpy tính nhanh hơn List ở lượt chạy là ~  6 lần!!


#Ví dụ: 3.4.3.1. Minh họa các phép toán cộng, trừ, nhân, chia sử dụng ufuncs

In [3]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
#Phép Cộng:Sử dụng hàm np.add() hoặc toán tử '+'.
Tong = np.add(arr1,arr2)
#hoặc tong = arr1+arr2
#Phép Trừ: Sử dụng hàm np.subtract() hoặc toán tử '-'.
Hieu = np.subtract(arr1,arr2)
#hoặc Tru = arr1-arr2
#Phép Nhân: Sử dụng hàm np.multiply() hoặc toán tử '*'
Tich = np.multiply(arr1,arr2)
#Hoặc arr1*arr2
#Phép Chia: Sử dụng hàm np.divide() hoặc toán tử '/'
Thuong = np.divide(arr1,arr2)
print("Tổng của arr1 + arr2 là:",Tong)
print("Hiệu của arr1 - arr2 là:",Hieu)
print("Tích của arr1 * arr2 là:",Tich)
print("Thương của arr1/arr2 là:",Thuong) 


Tổng của arr1 + arr2 là: [5 7 9]
Hiệu của arr1 - arr2 là: [-3 -3 -3]
Tích của arr1 * arr2 là: [ 4 10 18]
Thương của arr1/arr2 là: [0.25 0.4  0.5 ]


#vd 3.4.3.2 Hàm toán tử nhị phân

In [4]:
import numpy as np
arr1=np.random.rand(5)
arr1

array([0.80926224, 0.7574079 , 0.69999286, 0.94678427, 0.03850457])

In [5]:
arr2=np.random.rand(5)
arr2

array([0.00564819, 0.81749001, 0.42770199, 0.87700587, 0.98037765])

In [6]:
arr_maximum=np.maximum(arr1,arr2)
print("Mảng kết quả là:",arr_maximum)

Mảng kết quả là: [0.80926224 0.81749001 0.69999286 0.94678427 0.98037765]


#Ví dụ 3.4.3.3. Minh họa sử dụng các hàm đơn nguyên tổng quát (unary ufuncs) để
thực hiện các phép toán căn bậc hai, lũy thừa, logarit, giá trị tuyệt đối và một số hàm
số học và hàm logic khác trên mảng NumPy.

In [15]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
# Căn bậc hai của các phần tử trong mảng
kq_can_hai = np.sqrt(arr)
# Lũy thừa 2 của các phần tử trong mảng
kq_luy_thua_2 = np.power(arr, 2)
# Logarit tự nhiên (cơ số e) của các phần tử trong mảng
kq_Logarit = np.log(arr)
# Giá trị tuyệt đối của các phần tử trong mảng
kq_tri_tuyet_doi = np.abs(arr)
# Hàm logic NOT (đảo ngược giá trị) của các phần tử trong mảng
kq_not_logic = np.logical_not(arr)
#Hàm sin của các phần tử trong mảng
kq_sin=np.sin(arr)
print("Căn bậc hai của từng phần tử trong mảng là: ", kq_can_hai)
print("Lũy thừa bậc hai của từng phần tử trong mảng là: ", kq_luy_thua_2)
print("Logarit của từng phần tử trong mảng là: ", kq_Logarit)
print("Trị tuyệt đối của từng phần tử trong mảng là: ", kq_tri_tuyet_doi)
print("Kết quả đảo ngược giá trị của các phần tử trong mảng là:", kq_not_logic)
print("Kết quả hàm sin của các phần tử trong mảng là:", kq_sin)


Căn bậc hai của từng phần tử trong mảng là:  [1.         1.41421356 1.73205081 2.         2.23606798]
Lũy thừa bậc hai của từng phần tử trong mảng là:  [ 1  4  9 16 25]
Logarit của từng phần tử trong mảng là:  [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Trị tuyệt đối của từng phần tử trong mảng là:  [1 2 3 4 5]
Kết quả đảo ngược giá trị của các phần tử trong mảng là: [False False False False False]
Kết quả hàm sin của các phần tử trong mảng là: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


#Ví dụ: 3.4.4.1. Cộng hai mảng có cùng kích thước


In [10]:
import numpy as np
arr1 = np.array([0,1,2])
arr2 = np.array([5,5,5])
arr1 + arr2

array([5, 6, 7])

#Ví dụ 3.4.4.2.

In [11]:
import numpy as np
arr1 = np.array([0,1,2])
arr1 + 5

array([5, 6, 7])

#Ví dụ 3.4.4.3

In [12]:
import numpy as np
arr = np.array([0,1,2])
arr

array([0, 1, 2])

In [13]:
M=np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
arr + M

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])